### ISSUE TITLE
FR: UI Improvement

### ISSUE THREAD

**Issue by KAGEYAM4** [blacknon/hwatch#108]
Something similar to https://github.com/sachaos/viddy.

Currently UI is very congested if Terminal window is small ->

![image](https://github.com/blacknon/hwatch/assets/75798544/a24829b4-61e2-4bd0-b481-31a4179755f9)

**Comment by blacknon** [comment]
Backspace will hide the history window.

**Comment by blacknon** [comment]
For now, re check the entire UI.

- Change default display according to screen size (header/history pane display)
- Consider header display content

**Comment by KAGEYAM4** [comment]
Sorry, i missed your previous reply.

Would it be possible to have Boxes around text elements inorder to distinguish from other text and maybe some rearrangement of items. Similar to this or some other way -> 
![image](https://github.com/blacknon/hwatch/assets/75798544/4cf8bd48-30a8-4123-8945-621b800494e5)





--------------------------

Also i can make sepretage FR for this if you would like -> in viddy diff numbers are shown, like how many lines got added or removed. Which is very helpful to get an idea where things might have happened in past. 
![image](https://github.com/blacknon/hwatch/assets/75798544/d41f186d-6b54-42e5-8a6c-a70ae483cfcf)

**Comment by blacknon** [comment]
Not set history pane frame is my personal preference, and since it is supported by the library, it should be possible to adapt it immediately.

I think the following pattern is a possible way to implement it, so I will apply it as an option.
(Probably 1 if you want to make it optional.)

1. boarder in to frame the header and history pane
2. Change the background color of the header and history pane to make the breaks more visible

do not need to create a new Issue.

**Comment by blacknon** [comment]
Hi.
I updated it like this.
By default, changes can be made using the following shortcut keys.

- <kbd>B</kbd> ... with border 
- <kbd>S</kbd> ... with scroll bar
- <kbd>Shift</kbd> + <kbd>S</kbd> ... with summary

![Screenshot from 2024-06-09 19-08-56](https://github.com/blacknon/hwatch/assets/11777090/570c04b6-8c39-46e9-8278-e020a4069591)

**Comment by KAGEYAM4** [comment]
Yes this looks good. Thank you.
