### ISSUE TITLE
[Feature Request] Show center panel only, hiding other panels

### ISSUE THREAD

**Issue by pytkr** [blacknon/hwatch#63]
Hello!
This is a great command to use! 
I hope to show only center part of hwatch, namely, just like using it without hwatch and the screen will update as well.
Thus, size of console can be resized to be smaller, and multiple consoles opened side by side can be more concise to read.
Thanks!

**Comment by ilyagr** [comment]
I have a hacky implementation of this in https://github.com/ilyagr/hwatch/tree/hideui. I use it all the time, but it's not ready for prime time since, for instance, I need to pick better keyboard shortcuts and write the help. I was meaning to clean it up and send a pull request eventually (unsure when), but let me know if you'd prefer to do it.

The most difficult thing is how to deal with history when the UI isn't shown. The easiest thing to do would be to disable it. In my version, it is *not* disabled, which is useful but confusing. Eventually, there could be a minimal UI to tell the user if they are seeing a past state. I may or may not do that in the first version.

**Comment by ilyagr** [comment]
Also, thanks for making this! It's such a nice tool for watching `git log` and the like.

**Comment by ilyagr** [comment]
This branch is getting closer to being ready. You can now use `-t` command-line argument to start `hwatch` with UI hidden. I made a very minimal history interface that shows up when necessary to reduce confusion. 

I still need to change the keybindings and add help. For now, the keybindings are still Backspace and `u`.

See https://github.com/ilyagr/hwatch/releases/tag/ig-0.3.7d for binaries (they also have a couple of additional customizations that I probably won't submit).
