### ISSUE TITLE
Pagination support / Parameterized length

### ISSUE THREAD

**Issue by RobValentine** [blacknon/hwatch#96]
I understand that this may be out of scope but it would be good if hWatch could either support pagination of results or a parameter to pass in maximum length/number of lines.

Currently, hWatch seems to cut off at 56 lines. While that's usually enough, if I'm working with something large say:
`hwatch "kubectl get ns"` where the number of namespaces is sometimes 200 or more, hwatch only displays the first 56

**Comment by blacknon** [comment]
This is probably due to the inability to scroll all lines when there are long lines.

If there is a long line on the side of the library that is currently being used, it is not possible to retrieve the row that the line uses.
This is causing problems with getting the maximum number of rows that can be scrolled.

The method of response is under consideration.
